#!/bin/bash
echo "@shmadul's Blade 15 2 Finger Click Fix"
xinput set-prop 15 320 {1 1}
echo "Installing Untethered Solution"
sudo echo "#!/bin/bash
xinput set-prop 15 320 {1 1}" > /etc/init.d/fix
sudo chmod +x /etc/init.d/fix
echo "Untether Installed, 2 finger touch should be persistent"
